### ISSUE TITLE
Add 4.0.0-alpha.6 to www

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrap-cdn#841]
via: https://github.com/twbs/bootstrap/releases/download/4.0.0-alpha.6/bootstrap-4.0.0-alpha.6-dist.zip

```
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
```

**Comment by XhmikosR** [comment]
Cool. I'll check it out soon-ish. I assume we should merge to master after
that?

On Jan 6, 2017 19:43, "Justin Dorfman" <notifications@github.com> wrote:

via: https://github.com/twbs/bootstrap/releases/download/4.
0.0-alpha.6/bootstrap-4.0.0-alpha.6-dist.zip


<link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
crossorigin="anonymous">


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
crossorigin="anonymous"></script>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MaxCDN/bootstrap-cdn/issues/841>, or mute the thread

**Comment by jdorfman** [comment]
@XhmikosR yes =)

**Comment by XhmikosR** [comment]
Fixed in https://github.com/MaxCDN/bootstrap-cdn/commit/4853ada1af7b4a288c53ba88fe8909f513f68580

@jdorfman @jmervine: can you run `node integrity.js` and see if _config.yml has any changes? I'm getting different hashes for some of the old files which shouldn't happen.

**Comment by XhmikosR** [comment]
I'll merge to master after we solve this.

**Comment by jdorfman** [comment]
@XhmikosR checking

**Comment by XhmikosR** [comment]
Or it can be a line endings issue, quickly looking into it before I leave home.

**Comment by XhmikosR** [comment]
All right, it was a line endings issue. I'll merge to master now.

**Comment by jdorfman** [comment]
k
